In [2]:
import pandas as pd
import numpy as np

In [10]:
dflisting401 = pd.read_csv('raw/CRMLSListing202401.csv')
dflisting402 = pd.read_csv('raw/CRMLSListing202402.csv')
dfsold401 = pd.read_csv('raw/CRMLSSold202401.csv')
dfsold402 = pd.read_csv('raw/CRMLSSold202402.csv')

In [14]:
dflisting401.head()

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,90000.0,1075010398,miriamlara03@gmail.com,NaN,NaN,Miriam,Lara,34.097939,-117.909653,1045 N Azusa 61,...,NaN,NaN,2.0,Covina Valley Unified,91722,NaN,0.0,NaN,NaN,1045 N Azusa 61
1,1500000.0,1074974457,janelle@judsonre.com,NaN,NaN,Janelle,Judson,33.121241,-117.081614,NaN,...,NaN,NaN,NaN,NaN,92025,NaN,0.0,NaN,NaN,NaN
2,1340000.0,1074973329,haleh360@Gmail.com,NaN,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,False,NaN,NaN,90067,NaN,2105.0,177861.0,NaN,2220 Avenue Of The Stars 2704
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaN,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,0.0,False,3.0,Capistrano Unified,92677,NaN,254.0,5300.0,NaN,16 Palisades
4,3150000.0,1074936537,anader@dppre.com,NaN,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,NaN,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road

In [5]:
dflisting402.head()

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,1000.0,421654881,luann.hall@sbcglobal.net,NaN,NaN,Lu Ann,Hall,33.138645,-117.180289,823 Grand Avenue 203,...,NaN,NaN,NaN,NaN,92078,NaN,0.0,60112.8,NaN,823 Grand Avenue 203
1,799999.0,1075011484,Christina.sdsu12@gmail.com,NaN,NaN,Christina,Diab,NaN,NaN,10924 Via Banco,...,NaN,False,1.0,NaN,92126,NaN,195.0,720740.0,NaN,10924 Via Banco
2,820000.0,1075000634,ethan@c2realty.com,NaN,NaN,Ethan,Kolb,37.340056,-120.434070,2918 Dunn Road,...,1.0,False,0.0,Merced City,95340,NaN,0.0,95528.0,NaN,2918 Dunn Road
3,1300000.0,1074997455,jportillo@kw.com,NaN,NaN,Jason,Portillo,34.577993,-118.154162,1 Mile W Tierra Subida Q,...,NaN,False,NaN,NaN,93550,NaN,0.0,1744142.4,NaN,1 Mile W Tierra Subida Q
4,489999.0,1074990034,corey@murphyhousing.com,NaN,NaN,Corey,Murphy,33.141744,-117.091877,1421 N Broadway E,...,0.0,NaN,1.0,Escondido Union,92026,NaN,561.0,341510.4,NaN,1421 N Broadway E

In [6]:
dfsold401.head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,NaN,False,1.0,Other,94401,6472.0,NaN,NaN,CRMLS,CRMLS_MLSL
1,HighDesert,HighDesert,NaN,NaN,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,...,NaN,NaN,NaN,NaN,92394,NaN,52320.0,NaN,CRMLS,CRMLS_CRM
2,OrangeCounty,OrangeCounty,NaN,True,NaN,NaN,NaN,75000.0,529986282,Joe@9WINWIN.com,...,NaN,False,NaN,NaN,93240,NaN,217364.0,NaN,CRMLS,CRMLS_CRM
3,InlandValleys,InlandValleys,NaN,True,NaN,NaN,NaN,199000.0,529618166,carolthefinder@yahoo.com,...,NaN,False,NaN,NaN,92308,NaN,217800.0,NaN,CRMLS,CRMLS_CRM
4,SouthwestRiversideCounty,SouthwestRiversideCounty,NaN,True,NaN,NaN,NaN,19500.0,522614340,jtavisola@tavisola.com,...,NaN,False,NaN,NaN,93544,0.0,108883.0,NaN,CRMLS,CRMLS_CRM

In [7]:
dfsold402.head()

,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,LotSizeDimensions,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
0,"Carpet,Vinyl,Wood",True,NaN,NaN,False,1890000.0,547863987,catsnow1@gmail.com,2024-02-07,1249000.0,...,NaN,4.13,3.0,False,3.0,Kelseyville Unified,95451,0.0,179902.8,NaN
1,NaN,False,NaN,NaN,NaN,750000.0,544532864,becklandsales@aol.com,2024-02-15,374000.0,...,NaN,435600.00,NaN,NaN,NaN,Gilroy Unified,95020,NaN,435600.0,NaN
2,NaN,True,NaN,NaN,NaN,299000.0,541441508,HOMES@RICHRAGLAND.COM,2024-02-16,300000.0,...,NaN,437778.00,NaN,False,NaN,NaN,92592,0.0,437778.0,NaN
3,NaN,True,NaN,NaN,NaN,18750.0,540680208,realtorchrismurphy@gmail.com,2024-02-06,9000.0,...,NaN,111258.00,NaN,False,NaN,NaN,93591,0.0,111258.0,NaN
4,NaN,True,NaN,NaN,False,830000.0,532205379,anna@wallstreetsellsla.com,2024-02-02,730000.0,...,50x125,5402.00,NaN,False,NaN,NaN,90303,NaN,5402.0,NaN

Starting EDA

In [15]:
dflisting401

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,90000.0,1075010398,miriamlara03@gmail.com,NaN,NaN,Miriam,Lara,34.097939,-117.909653,1045 N Azusa 61,...,NaN,NaN,2.0,Covina Valley Unified,91722,NaN,0.0,NaN,NaN,1045 N Azusa 61
1,1500000.0,1074974457,janelle@judsonre.com,NaN,NaN,Janelle,Judson,33.121241,-117.081614,NaN,...,NaN,NaN,NaN,NaN,92025,NaN,0.0,NaN,NaN,NaN
2,1340000.0,1074973329,haleh360@Gmail.com,NaN,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,False,NaN,NaN,90067,NaN,2105.0,177861.0,NaN,2220 Avenue Of The Stars 2704
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaN,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,0.0,False,3.0,Capistrano Unified,92677,NaN,254.0,5300.0,NaN,16 Palisades
4,3150000.0,1074936537,anader@dppre.com,NaN,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,NaN,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27449,2850000.0,1045566949,rosieteddie@cox.net,2024-01-29,2824000.0,Rosie,Gross,32.990615,-117.215308,16050 Avenida Calma,...,2.0,NaN,2.0,San Dieguito Union,92091,Berkshire Hathaway HomeService,100.0,6624.0,NaN,16050 Avenida Calma
27450,1668000.0,1044575849,hollybuiRealty@gmail.com,2024-03-18,1680000.0,Holly,Bui,33.066445,-117.074284,3425 Lomas Serenas Dr,...,1.0,NaN,3.0,San Pasqual Union,92029,Allison James Estates & Homes,31.0,22215.6,NaN,3425 Lomas Serenas Dr
27451,1399990.0,1043760653,joe@porchlightsocal.com,2024-03-15,1270000.0,Joseph,Vahedi,33.228004,-117.247826,123 Flores Lane,...,2.0,NaN,2.0,Vista Unified,92083,eXp Realty of Southern CA,252.0,9897.0,NaN,123 Flores Lane
27452,969900.0,1040857564,homes@efrainachacon.com,2024-03-08,944900.0,Efrain,Chacon,33.233819,-117.009789,14845 Vesper Road,...,NaN,NaN,2.0,Valley Center - Pauma,92082,BBR Partners,0.0,108900.0,NaN,14845 Vesper Road
27453,1849000.0,1040106337,Jason.Daniels@Compass.com,2024-05-06,1549000.0,Jason,Daniels,33.128429,-117.147817,635 Sandy Lane,...,3.0,NaN,2.0,San Marcos Unified,92078,Compass,0.0,41817.6,NaN,635 Sandy Lane

In [34]:
dflisting401.columns

Index(['OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate',
       'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude',
       'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea',
       'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName',
       'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName',
       'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName',
       'BuyerAgentLastName', 'FireplacesTotal', 'AssociationFeeFrequency',
       'AboveGradeFinishedArea', 'ListingKeyNumeric', 'MLSAreaMajor',
       'TaxAnnualAmount', 'CountyOrParish', 'PropertyType.1', 'MlsStatus',
       'ElementarySchool', 'ListAgentFirstName.1', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'DaysOnMarket.1',
       'BuyerAgencyCompensationType', 'StreetNumberNumeric', 'LivingArea.1',
       'ListingId', 'BathroomsTotalInteger', 'City', 'BuyerAgencyCompensation',
       'TaxYear', 'BuildingAreaTotal', 'BedroomsTotal',
       'ContractStatusChangeDate', 'Longitude.1', 'ElementarySchoolDistrict',
       'CoBuyerAgentFirstName', 'PurchaseContractDate', 'ListingContractDate',
       'BelowGradeFinishedArea', 'BusinessType', 'Latitude.1', 'ListPrice.1',
       'StateOrProvince', 'CoveredSpaces', 'MiddleOrJuniorSchool',
       'FireplaceYN', 'Stories', 'HighSchool', 'Levels', 'ListAgentLastName.1',
       'CloseDate.1', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'BuyerOfficeName.1', 'AssociationFee', 'LotSizeSquareFeet',
       'MiddleOrJuniorSchoolDistrict', 'UnparsedAddress.1'],
      dtype='str')

In [44]:
# some columns have a `col.1`
col1list = []
for col in dflisting401.columns:
    if col[-2:] == '.1':
        print(col)
        col1list.append(col)

PropertyType.1
ListAgentFirstName.1
DaysOnMarket.1
LivingArea.1
Longitude.1
Latitude.1
ListPrice.1
ListAgentLastName.1
CloseDate.1
BuyerOfficeName.1
UnparsedAddress.1

In [52]:
for col1 in col1list:
    print(f'col1: {dflisting401[col1[:-2]].equals(dflisting401[col1])}')  # [:-2] to check original column without `.1`

col1: True
col1: True
col1: True
col1: True
col1: True
col1: True
col1: True
col1: True
col1: True
col1: True
col1: True

In [56]:
# seems these are duplicate columns
# checking for 402 listings dataset,

col1list2 = []
for col in dflisting402.columns:
    if col[-2:] == '.1':
        print(col)
        col1list2.append(col)
for col1 in col1list:
    print(f'col1: {dflisting401[col1[:-2]].equals(dflisting401[col1])}')  # [:-2] to check original column without `.1`

# still the same

PropertyType.1
ListAgentFirstName.1
DaysOnMarket.1
LivingArea.1
Longitude.1
Latitude.1
ListPrice.1
ListAgentLastName.1
CloseDate.1
BuyerOfficeName.1
UnparsedAddress.1
col1: True
col1: True
col1: True
col1: True
col1: True
col1: True
col1: True
col1: True
col1: True
col1: True
col1: True

In [33]:
dflisting401.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,...,Latitude.1,ListPrice.1,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
count,2.734900e+04,2.745400e+04,2.000100e+04,22233.000000,22271.000000,23743.000000,2.738100e+04,27454.000000,0.0,0.0,...,22233.000000,2.738100e+04,0.0,20230.000000,2.470100e+04,12990.000000,22053.000000,18889.000000,2.465900e+04,0.0
mean,1.003460e+06,1.057443e+09,7.853573e+05,34.189784,-117.983493,1881.864444,9.358645e+05,33.073905,NaN,NaN,...,34.189784,9.358645e+05,NaN,1.353782,1.089621e+05,1.928099,1.764658,185.083243,4.337150e+05,NaN
std,5.701279e+06,2.482638e+06,1.031606e+06,1.175846,2.086340,1444.543210,2.241971e+06,33.568712,NaN,NaN,...,1.175846,2.241971e+06,NaN,0.478154,4.917544e+06,1.481293,4.651844,436.887341,1.551623e+07,NaN
min,1.000000e+00,1.040106e+09,0.000000e+00,0.000000,-156.450240,0.000000,1.000000e+00,-58.000000,NaN,NaN,...,0.000000,1.000000e+00,NaN,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,NaN
25%,6.250000e+04,1.054642e+09,2.350000e+04,33.753374,-118.384770,1171.000000,6.000000e+04,7.000000,NaN,NaN,...,33.753374,6.000000e+04,NaN,1.000000,4.792000e+03,1.000000,1.000000,0.000000,5.170000e+03,NaN
50%,5.990000e+05,1.058383e+09,6.200000e+05,34.015428,-117.925718,1577.000000,5.990000e+05,20.000000,NaN,NaN,...,34.015428,5.990000e+05,NaN,1.000000,7.180000e+03,2.000000,2.000000,0.000000,7.405200e+03,NaN
75%,1.025000e+06,1.059331e+09,1.020000e+06,34.177017,-117.278870,2175.000000,1.000000e+06,52.000000,NaN,NaN,...,34.177017,1.000000e+06,NaN,2.000000,1.350300e+04,3.000000,2.000000,298.000000,1.622100e+04,NaN
max,7.759000e+08,1.075010e+09,3.845000e+07,45.786323,24.547506,43560.000000,1.100000e+08,812.000000,NaN,NaN,...,45.786323,1.100000e+08,NaN,2.000000,5.445000e+08,43.000000,500.000000,15000.000000,1.517979e+09,NaN

In [28]:
for i in dflisting401.isna().sum().items():
    print(f'{i[0]}: {i[-1]}')

OriginalListPrice: 105
ListingKey: 0
ListAgentEmail: 33
CloseDate: 7318
ClosePrice: 7453
ListAgentFirstName: 162
ListAgentLastName: 3
Latitude: 5221
Longitude: 5183
UnparsedAddress: 61
PropertyType: 0
LivingArea: 3711
ListPrice: 73
DaysOnMarket: 0
ListOfficeName: 0
BuyerOfficeName: 7648
CoListOfficeName: 21814
ListAgentFullName: 4
CoListAgentFirstName: 21863
CoListAgentLastName: 21852
BuyerAgentMlsId: 7397
BuyerAgentFirstName: 7469
BuyerAgentLastName: 7374
FireplacesTotal: 27454
AssociationFeeFrequency: 19623
AboveGradeFinishedArea: 27454
ListingKeyNumeric: 0
MLSAreaMajor: 2656
TaxAnnualAmount: 27235
CountyOrParish: 0
PropertyType.1: 0
MlsStatus: 0
ElementarySchool: 24838
ListAgentFirstName.1: 162
AttachedGarageYN: 9382
ParkingTotal: 2046
BuilderName: 26504
PropertySubType: 3765
LotSizeAcres: 2866
SubdivisionName: 18310
BuyerOfficeAOR: 7969
YearBuilt: 2542
DaysOnMarket.1: 0
BuyerAgencyCompensationType: 19
StreetNumberNumeric: 121
LivingArea.1: 3711
ListingId: 0
BathroomsTotalInteger: 2541
City: 46
BuyerAgencyCompensation: 39
TaxYear: 27417
BuildingAreaTotal: 23286
BedroomsTotal: 3597
ContractStatusChangeDate: 140
Longitude.1: 5183
ElementarySchoolDistrict: 27454
CoBuyerAgentFirstName: 25785
PurchaseContractDate: 6173
ListingContractDate: 0
BelowGradeFinishedArea: 27382
BusinessType: 27227
Latitude.1: 5221
ListPrice.1: 73
StateOrProvince: 2
CoveredSpaces: 27454
MiddleOrJuniorSchool: 24792
FireplaceYN: 4328
Stories: 7224
HighSchool: 23995
Levels: 5525
ListAgentLastName.1: 3
CloseDate.1: 7318
LotSizeDimensions: 25947
LotSizeArea: 2753
MainLevelBedrooms: 14464
NewConstructionYN: 3827
GarageSpaces: 5401
HighSchoolDistrict: 10783
PostalCode: 10
BuyerOfficeName.1: 7648
AssociationFee: 8565
LotSizeSquareFeet: 2795
MiddleOrJuniorSchoolDistrict: 27454
UnparsedAddress.1: 61

In [60]:
# looking at key MLS Fields
cols = ['OriginalListPrice', 'ListingKey', 'ListPrice', 'ClosePrice', 'LivingArea', 'BedroomsTotal', 'BathroomsTotalInteger', 'PropertyType', 'ListAgentFullName', 'DaysOnMarket']
keydflisting401 = dflisting401[cols]
keydflisting401

,OriginalListPrice,ListingKey,ListPrice,ClosePrice,LivingArea,BedroomsTotal,BathroomsTotalInteger,PropertyType,ListAgentFullName,DaysOnMarket
0,90000.0,1075010398,90000.0,NaN,960.0,4.0,1.0,ManufacturedInPark,Miriam Lara,0
1,1500000.0,1074974457,1500000.0,NaN,NaN,NaN,0.0,CommercialSale,Janelle Judson,0
2,1340000.0,1074973329,1340000.0,NaN,1301.0,2.0,2.0,Residential,Haleh Dowlatshahi,127
3,2500000.0,1074954552,2500000.0,NaN,2788.0,4.0,3.0,Residential,Renee Chen,1
4,3150000.0,1074936537,3150000.0,NaN,3250.0,6.0,4.0,Residential,Margaret Nader,1
...,...,...,...,...,...,...,...,...,...,...
27449,2850000.0,1045566949,2985000.0,2824000.0,2585.0,3.0,3.0,Residential,Rosie Gross,18
27450,1668000.0,1044575849,1685000.0,1680000.0,3004.0,5.0,3.0,Residential,Holly Bui,95
27451,1399990.0,1043760653,1295000.0,1270000.0,3360.0,4.0,4.0,Residential,Joseph Vahedi,174
27452,969900.0,1040857564,944900.0,944900.0,2284.0,4.0,2.0,Residential,Efrain Chacon,121
27453,1849000.0,1040106337,1549000.0,1549000.0,2085.0,3.0,2.0,Residential,Jason Daniels,82

In [61]:
keydflisting401.isna().sum()

OriginalListPrice         105
ListingKey                  0
ListPrice                  73
ClosePrice               7453
LivingArea               3711
BedroomsTotal            3597
BathroomsTotalInteger    2541
PropertyType                0
ListAgentFullName           4
DaysOnMarket                0
dtype: int64

In [29]:
dfsold401

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,NaN,False,1.0,Other,94401,6472.0,NaN,NaN,CRMLS,CRMLS_MLSL
1,HighDesert,HighDesert,NaN,NaN,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,...,NaN,NaN,NaN,NaN,92394,NaN,52320.0,NaN,CRMLS,CRMLS_CRM
2,OrangeCounty,OrangeCounty,NaN,True,NaN,NaN,NaN,75000.0,529986282,Joe@9WINWIN.com,...,NaN,False,NaN,NaN,93240,NaN,217364.0,NaN,CRMLS,CRMLS_CRM
3,InlandValleys,InlandValleys,NaN,True,NaN,NaN,NaN,199000.0,529618166,carolthefinder@yahoo.com,...,NaN,False,NaN,NaN,92308,NaN,217800.0,NaN,CRMLS,CRMLS_CRM
4,SouthwestRiversideCounty,SouthwestRiversideCounty,NaN,True,NaN,NaN,NaN,19500.0,522614340,jtavisola@tavisola.com,...,NaN,False,NaN,NaN,93544,0.0,108883.0,NaN,CRMLS,CRMLS_CRM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17971,OrangeCounty,OrangeCounty,NaN,NaN,NaN,NaN,NaN,2950000.0,1004078399,its94anthony@hotmail.com,...,NaN,NaN,NaN,NaN,90250,NaN,23757.0,NaN,CRMLS,CRMLS_CRM
17972,SierraNorthValley,SierraNorthValley,NaN,True,NaN,NaN,False,480000.0,1002802623,h2bshelton@yahoo.com,...,1.0,False,4.0,Chico Unified,95928,0.0,234353.0,NaN,CRMLS,CRMLS_CRM
17973,NorthSanDiegoCounty,NorthSanDiegoCounty,NaN,True,NaN,NaN,False,1600000.0,1002449803,tonytotanes@sbcglobal.net,...,7.0,NaN,2.0,Fallbrook Union,92028,0.0,23958.0,NaN,CRMLS,CRMLS_CRP
17974,SouthwestLosAngeles,SouthwestLosAngeles,NaN,False,NaN,NaN,NaN,299000.0,1001719107,TedBrass@TedBrass.com,...,NaN,False,NaN,NaN,92408,NaN,20000.0,NaN,CRMLS,CRMLS_CL
17975,Southland,Southland,NaN,True,NaN,NaN,NaN,449000.0,1001239968,kellymorganre@gmail.com,...,NaN,False,NaN,NaN,91307,NaN,29288.0,NaN,CRMLS,CRMLS_CRM

In [62]:
dfsold401.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,...,ElementarySchoolDistrict,BelowGradeFinishedArea,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
count,1.791700e+04,1.797600e+04,1.797600e+04,14558.000000,14577.000000,16428.000000,1.794200e+04,17976.000000,0.0,0.0,...,0.0,54.000000,0.0,14109.000000,1.617800e+04,9397.000000,15376.000000,12284.000000,1.616100e+04,0.0
mean,7.398353e+05,1.047535e+09,7.302208e+05,34.200542,-118.044628,1768.092075,7.210182e+05,46.737150,NaN,NaN,...,NaN,52.296296,NaN,1.352257,3.999246e+04,1.939449,1.722717,163.825585,7.105361e+05,NaN
std,1.170672e+06,2.300785e+07,3.274852e+06,1.164423,1.567344,1044.521664,1.104344e+06,73.468777,NaN,NaN,...,NaN,176.696801,NaN,0.477691,5.371497e+05,2.959578,4.180610,364.092171,3.147429e+07,NaN
min,0.000000e+00,4.214524e+08,1.300000e+00,1.000000,-156.450240,0.000000,1.400000e+00,-36.000000,NaN,NaN,...,NaN,0.000000,NaN,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,NaN
25%,9.500000e+03,1.046169e+09,8.587500e+03,33.750853,-118.383359,1152.000000,9.000000e+03,10.000000,NaN,NaN,...,NaN,0.000000,NaN,1.000000,4.792000e+03,1.000000,1.000000,0.000000,5.045000e+03,NaN
50%,5.500000e+05,1.048446e+09,5.400000e+05,34.008788,-117.932331,1538.000000,5.490000e+05,28.000000,NaN,NaN,...,NaN,0.000000,NaN,1.000000,7.000000e+03,2.000000,2.000000,0.000000,7.230000e+03,NaN
75%,9.000000e+05,1.052326e+09,9.030000e+05,34.176364,-117.332804,2099.000000,8.990000e+05,60.000000,NaN,NaN,...,NaN,0.000000,NaN,2.000000,1.142475e+04,3.000000,2.000000,265.000000,1.300400e+04,NaN
max,3.200000e+07,1.079167e+09,4.172550e+08,41.891034,2.000000,27396.000000,3.200000e+07,4049.000000,NaN,NaN,...,NaN,896.000000,NaN,2.000000,4.199620e+07,255.000000,500.000000,17220.000000,2.208318e+09,NaN

In [31]:
for i in dfsold401.isna().sum().items():
    print(f'{i[0]}: {i[-1]}')

BuyerAgentAOR: 7
ListAgentAOR: 7
Flooring: 7860
ViewYN: 1760
WaterfrontYN: 17966
BasementYN: 17711
PoolPrivateYN: 2518
OriginalListPrice: 59
ListingKey: 0
ListAgentEmail: 13
CloseDate: 0
ClosePrice: 0
ListAgentFirstName: 105
ListAgentLastName: 0
Latitude: 3418
Longitude: 3399
UnparsedAddress: 42
PropertyType: 0
LivingArea: 1548
ListPrice: 34
DaysOnMarket: 0
ListOfficeName: 0
BuyerOfficeName: 222
CoListOfficeName: 14539
ListAgentFullName: 2
CoListAgentFirstName: 14564
CoListAgentLastName: 14554
BuyerAgentMlsId: 34
BuyerAgentFirstName: 86
BuyerAgentLastName: 5
FireplacesTotal: 17976
AssociationFeeFrequency: 13039
AboveGradeFinishedArea: 17976
ListingKeyNumeric: 0
MLSAreaMajor: 1739
TaxAnnualAmount: 17868
CountyOrParish: 0
MlsStatus: 0
ElementarySchool: 16150
AttachedGarageYN: 5455
ParkingTotal: 1211
BuilderName: 17282
PropertySubType: 1664
LotSizeAcres: 1863
SubdivisionName: 11741
BuyerOfficeAOR: 416
YearBuilt: 934
StreetNumberNumeric: 72
ListingId: 0
BathroomsTotalInteger: 1075
City: 19
TaxYear: 17958
BuildingAreaTotal: 15505
BedroomsTotal: 1501
ContractStatusChangeDate: 712
ElementarySchoolDistrict: 17976
CoBuyerAgentFirstName: 16601
PurchaseContractDate: 424
ListingContractDate: 2
BelowGradeFinishedArea: 17922
BusinessType: 17910
StateOrProvince: 0
CoveredSpaces: 17976
MiddleOrJuniorSchool: 16116
FireplaceYN: 1888
Stories: 3867
HighSchool: 15509
Levels: 2803
LotSizeDimensions: 17023
LotSizeArea: 1798
MainLevelBedrooms: 8579
NewConstructionYN: 2308
GarageSpaces: 2600
HighSchoolDistrict: 6129
PostalCode: 12
AssociationFee: 5692
LotSizeSquareFeet: 1815
MiddleOrJuniorSchoolDistrict: 17976
OriginatingSystemName: 0
OriginatingSystemSubName: 0

In [19]:
dfListings = pd.DataFrame()
listings = []
for i in range(4, 5 + 1):
    for m in range(1, 12 + 1):
        temp = pd.read_csv(f'raw/CRMLSListing202{i}{m:02d}.csv')
        print(f'Shape of CRMLSListing202{i}{m:02d}: {temp.shape}')
        listings.append(temp)

# Since only 601 and 602,
for i in range(1, 2 + 1):
    temp = pd.read_csv(f'raw/CRMLSListing20260{i}.csv')
    print(f'Shape of CRMLSListing20260{i}: {temp.shape}')
    listings.append(temp)

dfListings = pd.concat(listings)
print(f'Concatenated Dataframe size: dfListings.shape')
dfListings = dfListings[dfListings['PropertyType'] == 'Residential']
print(dfListings.shape)

dfListings.to_csv('CRMLSListing.csv', index=False)

(814874, 84)

In [20]:
dfSold = pd.DataFrame()
sold = []
for i in range(4, 5 + 1):
    for m in range(1, 12 + 1):
        temp = pd.read_csv(f'raw/CRMLSSold202{i}{m:02d}.csv')
        sold.append(temp)

# Since only 601 and 602,
for i in range(1, 2 + 1):
    temp = pd.read_csv(f'raw/CRMLSListing20260{i}.csv')
    sold.append(temp)

dfSold = pd.concat(sold)
dfSold = dfSold[dfSold['PropertyType'] == 'Residential']
print(dfSold.shape)

dfSold.to_csv('CRMLSSold.csv', index=False)

/var/folders/jk/ll2fwx_55klc6t5gz7x_24440000gn/T/ipykernel_11691/3476883897.py:5: DtypeWarning: Columns (0: WaterfrontYN, 1: ElementarySchool, 2: BuilderName, 3: CoBuyerAgentFirstName, 4: PostalCode) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(f'raw/CRMLSSold202{i}{m:02d}.csv')
/var/folders/jk/ll2fwx_55klc6t5gz7x_24440000gn/T/ipykernel_11691/3476883897.py:5: DtypeWarning: Columns (0: WaterfrontYN) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(f'raw/CRMLSSold202{i}{m:02d}.csv')

(600234, 95)