In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
listingsdf = pd.read_csv('filtered/filteredListings.csv')
solddf = pd.read_csv('filtered/filteredSold.csv')

/var/folders/jk/ll2fwx_55klc6t5gz7x_24440000gn/T/ipykernel_38253/2462508386.py:1: DtypeWarning: Columns (0: ListAgentEmail, 1: BuyerAgencyCompensationType) have mixed types. Specify dtype option on import or set low_memory=False.
  listingsdf = pd.read_csv('filtered/filteredListings.csv')
/var/folders/jk/ll2fwx_55klc6t5gz7x_24440000gn/T/ipykernel_38253/2462508386.py:2: DtypeWarning: Columns (0: BuyerAgentAOR, 1: ListAgentAOR, 2: FireplaceYN, 3: OriginatingSystemName, 4: OriginatingSystemSubName, 5: BuyerAgencyCompensationType, 6: latfilled, 7: lonfilled) have mixed types. Specify dtype option on import or set low_memory=False.
  solddf = pd.read_csv('filtered/filteredSold.csv')

In [60]:
display(listingsdf.head())
display(listingsdf.columns)
display(listingsdf.describe())

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,1340000.0,1074973329,haleh360@Gmail.com,NaN,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,False,NaN,NaN,90067,NaN,2105.00,177861.0,NaN,2220 Avenue Of The Stars 2704
1,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaN,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,0.0,False,3.0,Capistrano Unified,92677,NaN,254.00,5300.0,NaN,16 Palisades
2,3150000.0,1074936537,anader@dppre.com,NaN,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,NaN,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road
3,3090000.0,1074917818,QIANYU0607@GMAIL.COM,NaN,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,...,1.0,False,4.0,Walnut Valley Unified,91765,NaN,295.95,58232.0,NaN,2250 Indian Creek Road
4,12725000.0,1074143166,jeff.williams@pacificsir.com,NaN,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,...,3.0,False,2.0,Newport Mesa Unified,92662,NaN,0.00,2250.0,NaN,317 E. Bayfront

Index(['OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate',
       'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude',
       'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea',
       'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName',
       'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName',
       'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName',
       'BuyerAgentLastName', 'FireplacesTotal', 'AssociationFeeFrequency',
       'AboveGradeFinishedArea', 'ListingKeyNumeric', 'MLSAreaMajor',
       'TaxAnnualAmount', 'CountyOrParish', 'PropertyType.1', 'MlsStatus',
       'ElementarySchool', 'ListAgentFirstName.1', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'DaysOnMarket.1',
       'BuyerAgencyCompensationType', 'StreetNumberNumeric', 'LivingArea.1',
       'ListingId', 'BathroomsTotalInteger', 'City', 'BuyerAgencyCompensation',
       'TaxYear', 'BuildingAreaTotal', 'BedroomsTotal',
       'ContractStatusChangeDate', 'Longitude.1', 'ElementarySchoolDistrict',
       'CoBuyerAgentFirstName', 'PurchaseContractDate', 'ListingContractDate',
       'BelowGradeFinishedArea', 'BusinessType', 'Latitude.1', 'ListPrice.1',
       'StateOrProvince', 'CoveredSpaces', 'MiddleOrJuniorSchool',
       'FireplaceYN', 'Stories', 'HighSchool', 'Levels', 'ListAgentLastName.1',
       'CloseDate.1', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'BuyerOfficeName.1', 'AssociationFee', 'LotSizeSquareFeet',
       'MiddleOrJuniorSchoolDistrict', 'UnparsedAddress.1'],
      dtype='str')

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,...,Latitude.1,ListPrice.1,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
count,5.144630e+05,5.151980e+05,1.407840e+05,435328.000000,435328.000000,5.146700e+05,5.151980e+05,515198.000000,0.0,0.0,...,435328.000000,5.151980e+05,0.0,425479.000000,4.734220e+05,280402.000000,486606.000000,391325.000000,4.732520e+05,0.0
mean,1.396478e+06,1.102343e+09,1.198837e+06,34.593478,-118.451065,1.980128e+03,1.310962e+06,19.667074,NaN,NaN,...,34.593478,1.310962e+06,NaN,1.370467,4.736339e+04,2.049450,1.844736,269.800573,4.117880e+05,NaN
std,7.434846e+06,2.838914e+07,4.357490e+06,2.007680,3.469609,2.394131e+04,2.349644e+06,27.144469,NaN,NaN,...,2.007680,2.349644e+06,NaN,0.482930,2.229488e+06,6.585476,3.880750,2421.997582,2.089153e+07,NaN
min,0.000000e+00,1.018357e+09,5.250000e+02,-117.472493,-159.475987,0.000000e+00,1.000000e+02,-58.000000,NaN,NaN,...,-117.472493,1.000000e+02,NaN,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,NaN
25%,5.850000e+05,1.077046e+09,6.000000e+05,33.739774,-118.653069,1.246000e+03,5.800000e+05,5.000000,NaN,NaN,...,33.739774,5.800000e+05,NaN,1.000000,5.000000e+03,1.000000,1.000000,0.000000,5.227000e+03,NaN
50%,8.490000e+05,1.103183e+09,8.500000e+05,34.051918,-118.022031,1.668000e+03,8.399990e+05,11.000000,NaN,NaN,...,34.051918,8.399990e+05,NaN,1.000000,7.192000e+03,2.000000,2.000000,125.000000,7.405000e+03,NaN
75%,1.388000e+06,1.119000e+09,1.350000e+06,34.462447,-117.236720,2.297000e+03,1.375000e+06,23.000000,NaN,NaN,...,34.462447,1.375000e+06,NaN,2.000000,1.200000e+04,3.000000,2.000000,400.000000,1.352700e+04,NaN
max,1.390000e+09,1.155898e+09,8.200000e+08,737.000000,329.000000,1.702132e+07,1.950000e+08,731.000000,NaN,NaN,...,737.000000,1.950000e+08,NaN,2.000000,9.187423e+08,3333.000000,600.000000,968348.000000,7.638115e+09,NaN

In [61]:
display(solddf.head())
display(solddf.columns)
display(solddf.describe())

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,ListAgentFirstName.1,DaysOnMarket.1,LivingArea.1,Longitude.1,Latitude.1,ListPrice.1,ListAgentLastName.1,CloseDate.1,BuyerOfficeName.1,UnparsedAddress.1
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SanDiego,SanDiego,NaN,False,NaN,NaN,False,759900.0,522107581,mdarwich12@gmail.com,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SanDiego,SanDiego,NaN,False,NaN,NaN,False,739900.0,510919001,mdarwich12@gmail.com,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mlslistings,Mlslistings,NaN,False,NaN,NaN,NaN,NaN,1079166779,davidmartz@compass.com,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Southland,Southland,NaN,False,NaN,NaN,False,1890500.0,1075037759,karen.klein@theagencyre.com,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'ListAgentEmail', 'CloseDate', 'ClosePrice', 'ListAgentFirstName',
       'ListAgentLastName', 'Latitude', 'Longitude', 'UnparsedAddress',
       'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket',
       'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict',
       'OriginatingSystemName', 'OriginatingSystemSubName',
       'BuyerAgencyCompensationType', 'BuyerAgencyCompensation', 'latfilled',
       'lonfilled', 'PropertyType.1', 'ListAgentFirstName.1', 'DaysOnMarket.1',
       'LivingArea.1', 'Longitude.1', 'Latitude.1', 'ListPrice.1',
       'ListAgentLastName.1', 'CloseDate.1', 'BuyerOfficeName.1',
       'UnparsedAddress.1'],
      dtype='str')

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,...,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,BuyerAgencyCompensation,DaysOnMarket.1,LivingArea.1,Longitude.1,Latitude.1,ListPrice.1
count,4.014660e+05,4.021550e+05,3.662360e+05,386071.000000,386071.000000,4.019020e+05,4.021550e+05,402155.000000,0.0,0.0,...,384189.000000,309893.000000,3.705670e+05,0.0,46125.000000,42684.000000,42641.000000,42208.000000,42208.000000,4.268400e+04
mean,1.251955e+06,1.097227e+09,1.190388e+06,34.656239,-118.569651,1.915107e+03,1.163524e+06,34.279166,NaN,NaN,...,1.857790,240.649629,3.218867e+05,NaN,221.929675,17.284720,1981.880331,-118.499687,34.631344,1.367804e+06
std,7.057552e+06,3.127780e+07,6.005548e+06,1.711698,3.068037,2.686684e+04,1.540076e+06,50.252142,NaN,NaN,...,3.818315,1766.672365,1.559538e+07,NaN,2590.406598,14.429032,1317.656445,3.773931,1.735598,2.625130e+06
min,0.000000e+00,4.216785e+08,0.000000e+00,-117.472493,-177.646696,0.000000e+00,5.250000e+02,-288.000000,NaN,NaN,...,0.000000,0.000000,0.000000e+00,NaN,0.000000,-17.000000,0.000000,-155.633577,-12.100375,6.500000e+03
25%,5.850000e+05,1.075141e+09,5.790000e+05,33.738228,-118.890453,1.246000e+03,5.790000e+05,7.000000,NaN,NaN,...,2.000000,0.000000,5.227000e+03,NaN,2.000000,7.000000,1248.000000,-118.821319,33.731681,5.750000e+05
50%,8.290000e+05,1.095268e+09,8.250000e+05,34.048731,-118.021602,1.644000e+03,8.200000e+05,18.000000,NaN,NaN,...,2.000000,100.000000,7.259000e+03,NaN,2.500000,14.500000,1686.000000,-118.042985,34.049705,8.380000e+05
75%,1.299888e+06,1.117687e+09,1.300000e+06,34.561475,-117.267220,2.227000e+03,1.298000e+06,43.000000,NaN,NaN,...,2.000000,375.000000,1.202950e+04,NaN,2.500000,26.000000,2341.000000,-117.234792,34.537769,1.395000e+06
max,1.390000e+09,1.155898e+09,9.895000e+08,56.130366,329.000000,1.702132e+07,1.700000e+08,12430.000000,NaN,NaN,...,600.000000,750000.000000,2.208318e+09,NaN,100000.000000,390.000000,47044.000000,118.140030,46.344135,1.700000e+08

In [62]:
'''
some columns seem to have a column.1 name
'''

# checking if they are duplicates for listings
for col in listingsdf.columns:
    if col[-2:] == '.1':
        print(f'Is {col} a duplicate?\n{listingsdf[col[:-2]].equals(listingsdf[col])}')

print()

# checking if they are duplicates for sold
for col in solddf.columns:
    if col[-2:] == '.1':
        print(f'Is {col} a duplicate?\n{solddf[col[:-2]].equals(solddf[col])}')

Is PropertyType.1 a duplicate?
True
Is ListAgentFirstName.1 a duplicate?
True
Is DaysOnMarket.1 a duplicate?
True
Is LivingArea.1 a duplicate?
True
Is Longitude.1 a duplicate?
True
Is Latitude.1 a duplicate?
True
Is ListPrice.1 a duplicate?
True
Is ListAgentLastName.1 a duplicate?
True
Is CloseDate.1 a duplicate?
True
Is BuyerOfficeName.1 a duplicate?
True
Is UnparsedAddress.1 a duplicate?
True

Is PropertyType.1 a duplicate?
False
Is ListAgentFirstName.1 a duplicate?
False
Is DaysOnMarket.1 a duplicate?
False
Is LivingArea.1 a duplicate?
False
Is Longitude.1 a duplicate?
False
Is Latitude.1 a duplicate?
False
Is ListPrice.1 a duplicate?
False
Is ListAgentLastName.1 a duplicate?
False
Is CloseDate.1 a duplicate?
False
Is BuyerOfficeName.1 a duplicate?
False
Is UnparsedAddress.1 a duplicate?
False

In [63]:
# seems they are only duplicates for listings, not sold
# checking distributions
for col in solddf.columns:
    if col[-2:] == '.1':
        print(f'Null values in {col[:-2]}:', solddf[col[:-2]].isna().sum())
        print(f'Null values in {col}:', solddf[col].isna().sum())
        print()
# orders of magnitude more missing values in column.1
# dropped duplicates in listingsdf in script.py

Null values in PropertyType: 0
Null values in PropertyType.1: 359471

Null values in ListAgentFirstName: 3075
Null values in ListAgentFirstName.1: 359736

Null values in DaysOnMarket: 0
Null values in DaysOnMarket.1: 359471

Null values in LivingArea: 253
Null values in LivingArea.1: 359514

Null values in Longitude: 16084
Null values in Longitude.1: 359947

Null values in Latitude: 16084
Null values in Latitude.1: 359947

Null values in ListPrice: 0
Null values in ListPrice.1: 359471

Null values in ListAgentLastName: 36
Null values in ListAgentLastName.1: 359472

Null values in CloseDate: 34284
Null values in CloseDate.1: 393755

Null values in BuyerOfficeName: 40948
Null values in BuyerOfficeName.1: 394329

Null values in UnparsedAddress: 379
Null values in UnparsedAddress.1: 359526

In [64]:
# key columns as defined by the primer
# these columns should not be dropped even if there are a large number of missing values
keycols = set(('ListingKey', 
           'ListingContractDate', 
           'ListPrice',
           'ClosePrice',
           'PurchaseContractDate',
           'CloseDate',
           'LivingArea',
           'BedroomsTotal',
           'BathroomsTotalInteger',
           'Longitude',
           'Latitude',
           'UnparsedAddress',
           'ListAgentAOR'
           'DaysOnMarket'))

In [65]:
# identifying columns with >90% missing values

# listings
for col in listingsdf.columns:
    if listingsdf[col].isna().sum() > 0.90:
        if col in keycols:
            print(f'Key column in Listings with >90% missing values: {col}')
            continue
        listingsdf.drop(columns=[col], inplace=True)

print()

# sold
for col in solddf.columns:
    if solddf[col].isna().sum() > 0.90:
        if col in keycols:
            print(f'Key column in Sold with >90% missing values: {col}')
            continue
        solddf.drop(columns=[col], inplace=True)

Key column in Listings with >90% missing values: CloseDate
Key column in Listings with >90% missing values: ClosePrice
Key column in Listings with >90% missing values: Latitude
Key column in Listings with >90% missing values: Longitude
Key column in Listings with >90% missing values: UnparsedAddress
Key column in Listings with >90% missing values: LivingArea
Key column in Listings with >90% missing values: BathroomsTotalInteger
Key column in Listings with >90% missing values: BedroomsTotal
Key column in Listings with >90% missing values: PurchaseContractDate

Key column in Sold with >90% missing values: CloseDate
Key column in Sold with >90% missing values: ClosePrice
Key column in Sold with >90% missing values: Latitude
Key column in Sold with >90% missing values: Longitude
Key column in Sold with >90% missing values: UnparsedAddress
Key column in Sold with >90% missing values: LivingArea
Key column in Sold with >90% missing values: BathroomsTotalInteger
Key column in Sold with >90% missing values: BedroomsTotal
Key column in Sold with >90% missing values: PurchaseContractDate
Key column in Sold with >90% missing values: ListingContractDate

In [66]:
# CloseDate and ClosePrice have a large number of missing values
# The Sold dataframe has a large number of missing values in key columns. 
# This makes sense because not every listing would have been sold yet. 
# The data can be extracted from the listings dataframe for now.

In [67]:
toDropL = set()
for col in listingsdf.columns:
    if col[-2:] == '.1':
        toDropL.add(col)
    if listingsdf[col].isna().sum() > 0.90:
        if col in keycols:
            print(f'Key column in Listings with >90% missing values: {col}')
            continue
        else:
            toDropL.add(col)
listingsdf.drop(columns=toDropL, inplace=True)

Key column in Listings with >90% missing values: CloseDate
Key column in Listings with >90% missing values: ClosePrice
Key column in Listings with >90% missing values: Latitude
Key column in Listings with >90% missing values: Longitude
Key column in Listings with >90% missing values: UnparsedAddress
Key column in Listings with >90% missing values: LivingArea
Key column in Listings with >90% missing values: BathroomsTotalInteger
Key column in Listings with >90% missing values: BedroomsTotal
Key column in Listings with >90% missing values: PurchaseContractDate

In [68]:
toDropS = set()
for col in solddf.columns:
    if col[-2:] == '.1':
        toDropS.add(col)
    if solddf[col].isna().sum() > 0.90:
        if col in keycols:
            print(f'Key column in Listings with >90% missing values: {col}')
            continue
        else:
            toDropS.add(col)
solddf.drop(columns=toDropS, inplace=True)

Key column in Listings with >90% missing values: CloseDate
Key column in Listings with >90% missing values: ClosePrice
Key column in Listings with >90% missing values: Latitude
Key column in Listings with >90% missing values: Longitude
Key column in Listings with >90% missing values: UnparsedAddress
Key column in Listings with >90% missing values: LivingArea
Key column in Listings with >90% missing values: BathroomsTotalInteger
Key column in Listings with >90% missing values: BedroomsTotal
Key column in Listings with >90% missing values: PurchaseContractDate

In [69]:
listingsdf.dtypes

ListingKey                 int64
CloseDate                    str
ClosePrice               float64
Latitude                 float64
Longitude                float64
UnparsedAddress              str
PropertyType                 str
LivingArea               float64
ListPrice                float64
DaysOnMarket               int64
ListOfficeName               str
ListingKeyNumeric          int64
CountyOrParish               str
MlsStatus                    str
ListingId                    str
BathroomsTotalInteger    float64
BedroomsTotal            float64
PurchaseContractDate         str
ListingContractDate          str
dtype: object

In [70]:
solddf.dtypes

ListingKey                 int64
CloseDate                    str
ClosePrice               float64
Latitude                 float64
Longitude                float64
UnparsedAddress              str
PropertyType                 str
LivingArea               float64
ListPrice                float64
DaysOnMarket               int64
ListOfficeName               str
ListingKeyNumeric          int64
CountyOrParish               str
MlsStatus                    str
ListingId                    str
BathroomsTotalInteger    float64
BedroomsTotal            float64
PurchaseContractDate         str
ListingContractDate          str
dtype: object

In [71]:
# finding all columns that need to be converted to datetime format in sold
datecols = []
for col in listingsdf:
    if 'Date' in col:
        datecols.append(col)
datecols

['CloseDate', 'PurchaseContractDate', 'ListingContractDate']

In [72]:
# finding all columns that need to be converted to datetime format in listings
datecols = []
for col in solddf:
    if 'Date' in col:
        datecols.append(col)
datecols

['CloseDate', 'PurchaseContractDate', 'ListingContractDate']

In [78]:
listingsdf['Price Ratio'] = listingsdf['ClosePrice'] / listingsdf['ListPrice']
listingsdf['Price Ratio']

0         True
1         True
2         True
3         True
4         True
          ...
515193    True
515194    True
515195    True
515196    True
515197    True
Name: Price Ratio, Length: 515198, dtype: bool

In [81]:
solddf['Price Ratio'] = solddf['ClosePrice'] / solddf['ListPrice']

np.float64(0.08931630838855666)

In [112]:
solddf['YrMo'] = pd.to_datetime(solddf['CloseDate']).dt.to_period('M')
solddf['YrMo']

0         2024-01
1         2024-01
2         2024-01
3         2024-01
4         2024-01
           ...
402150        NaT
402151        NaT
402152        NaT
402153        NaT
402154        NaT
Name: YrMo, Length: 402155, dtype: period[M]

In [ ]:
# look into making everything functions so I don't have to rewrite code for listings and sold!

In [ ]:
# fix script.py ordering...

In [10]:
solddf['ClosePrice'].isna().sum() / solddf.shape[0]

np.float64(5.563731149383399e-06)